package risiko.net;

public enum ClientState{
	WAIT_FOR_CONFIGURATION,
	CONNECTION_REFUSED,
	CONFIGURED,
	TURN_ASSIGNED,
	REINFORCEMENT,
	UNITS_POSITIONED,
	END_REINFORCEMENT,
	ATTACK_PHASE,
	AFTER_ATTACK,
	NEW_DISPOSITION,
	GAME_DISCONNECTION
}
